apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-instance
          image: nginx
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app/log
              name: log-volume
        - name: filebeat
          image: elastic/filebeat:6.5.4
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
              name: filebeat-nginx-configmap
            - mountPath: /app/log
              name: log-volume

      volumes:
        - name: log-volume
          emptyDir: {}
        - name: filebeat-nginx-configmap
          configMap:
            name: filebeat-nginx

# kubectl create configmap filebeat-nginx-configmap --from-file=filebeat.yml 