apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-deployment
spec:
    replicas: 1
    selector:
      matchLabels:
        app: redis-pod
    template:
      metadata:
        labels:
          app: redis-pod
      spec:
        containers:
        - name: redis
          image: redis
          resources:
            requests:
              cpu: 100m              #限制cpu的数量为0.1个
              memory: 100Mi      #限制内存为100M
          ports:
          - containerPort: 6379
          volumeMounts:
          - name: redis-config
            mountPath: /etc/config
        volumes:
          - name: redis-config
            configMap:
              name: redis-config