apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
    - name: redis
      image: redis:5.0.3
      # command: ["/bin/sh", "-c", "cat /etc/config/special.how"]
      volumeMounts:
      - name: redis-config
        mountPath: /etc/config
      ports:
      - containerPort: 6379
  volumes:
    - name: redis-config
      configMap:
        name: redis-config