apiVersion: v1
kind: Service
metadata:
    name: mysql-svc
    labels:
        tier: mysql
spec:
    type: NodePort
    selector:
        tier: mysql
    ports:
        - name: mysql-port
          port: 3306
          targetPort: 3306
          nodePort: 30306


