apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: ubuntu
spec:
  containers:
    - name: ubuntu-instance
      image: ubuntu
      imagePullPolicy: IfNotPresent
      command: ['sh','-c','echo The app is running! && sleep 3600;']